const sellerLocation = [
	{ value: 'US', content: 'United States' },
	{ value: 'AT', content: 'Austria' },
	{ value: 'BE', content: 'Belgium' },
	{ value: 'BG', content: 'Bulgaria' },
	{ value: 'CA', content: 'Canada' },
	{ value: 'CN', content: 'China' },
	{ value: 'HR', content: 'Croatia' },
	{ value: 'CY', content: 'Cyprus' },
	{ value: 'CZ', content: 'Czech Republic' },
	{ value: 'DK', content: 'Denmark' },
	{ value: 'EE', content: 'Estonia' },
	{ value: 'FI', content: 'Finland' },
	{ value: 'FR', content: 'France' },
	{ value: 'DE', content: 'Germany' },
	{ value: 'GR', content: 'Greece' },
	{ value: 'GU', content: 'Guam' },
	{ value: 'HK', content: 'Hong Kong' },
	{ value: 'HU', content: 'Hungary' },
	{ value: 'IT', content: 'Italy' },
	{ value: 'LV', content: 'Latvia' },
	{ value: 'LT', content: 'Lithuania' },
	{ value: 'LU', content: 'Luxembourg' },
	{ value: 'MY', content: 'Malaysia' },
	{ value: 'MT', content: 'Malta' },
	{ value: 'NL', content: 'Netherlands' },
	{ value: 'PH', content: 'Philippines' },
	{ value: 'PL', content: 'Poland' },
	{ value: 'PT', content: 'Portugal' },
	{ value: 'RO', content: 'Romania' },
	{ value: 'SG', content: 'Singapore' },
	{ value: 'SK', content: 'Slovakia' },
	{ value: 'SI', content: 'Slovenia' },
	{ value: 'ES', content: 'Spain' },
	{ value: 'SE', content: 'Sweden' },
	{ value: 'GB', content: 'United Kingdom' },
	{ value: 'other', content: 'Other' },
];

const formOptions = {
	sellerLocation,
};

export default formOptions;
